### ISSUE TITLE
Update to latest go version

### ISSUE THREAD

**Issue by andrewsykim** [cloudnativelabs/kube-router#802] opened 2019-10-21 14:55 UTC
kube-router is currently being built on go v1.10.8

```
$ docker run -ti cloudnativelabs/kube-router:v0.4.0-rc1 -V
Running /usr/local/bin/kube-router version v0.4.0-rc1, built on 2019-10-14T12:08:16+0530, go1.10.8
```

We should update to at least the same version of Go that Kubernetes is using.

**Comment by aauren** [comment] 2020-04-25 08:13
Closing as duplicate of #636

**Closed by aauren** 2020-04-25 08:13 UTC
Labels: help wanted, p1
