### ISSUE TITLE
Little issue in a link on the documentation website

### ISSUE THREAD

**Issue by PopiBrossard** [cloudnativelabs/kube-router#1257] opened 2022-02-28 10:58 UTC
Dear maintainer,
**What happened?**
When I'm on the documentation website https://www.kube-router.io/docs/, and I click in the left menu on "User Guide" I've got a HTTP 404 error.

It's because this menu entry redirect to `https://www.kube-router.io/user-guide/` instead of `https://www.kube-router.io/docs/user-guide/` (missing `/docs` in the URL).

**What did you expect to happen?**
It should show the correct page without an HTTP error

**How can we reproduce the behavior you experienced?**
1. Go to https://www.kube-router.io/docs/
2. Click "User Guide" in the left menu

** System Information (please complete the following information):**
If it helps, I'm running Firefox 97.0.

**Additional context**
I'm sorry if it's not the good place to report this little issue about the documentation website.

**Comment by aauren** [comment] 2022-03-11 17:58
Thanks for reporting, this unfortunately an issue that has been around for a while.

Recently, I found out though that the documentation was setup and hosted out of the kube-router.io project that is also part of cloudnativelabs.

Now that I know that, this issue should be fixed by: https://github.com/cloudnativelabs/kube-router.io/pull/33

Closing this specific issue as it is a duplicate of a much older issue for this same topic: #814

**Closed by aauren** 2022-03-11 17:58 UTC
Labels: bug
