### ISSUE TITLE
kuber-router does not work with loadbalancer

### ISSUE THREAD

**Issue by tiukhtinvladimir** [cloudnativelabs/kube-router#310] opened 2018-02-16 15:33 UTC
MetalLB - load balancer for bare metal installations. It works perfect with kube-proxy but not with kube-router. Help! I like kube-router - do not want go back to kube-proxy

**Comment by tiukhtinvladimir** [comment] 2018-02-16 17:03
I found out that kube-router does not respect service with type loadbalancer and not create ipvs rules for this

**Comment by murali-reddy** [comment] 2018-02-16 17:25
@tiukhtinvladimir Yes, it does not supprt service type LoadBalancer yet. There is an issue opened for it https://github.com/cloudnativelabs/kube-router/issues/242. However kube-router supports advertising cluster-ip and external-ip to the BGP peers. You could actually do ECMP load balancing. All the necessary functionality is there, it just needs to be made available through LoadBalancer service type as well.

@roffe did try to make kube-router work with metallb. I am afraid, at this point MetalLb and kube-router may not work to gether. Same node can not have two BGP speakers (kube-router and metal LB). Also BGP export policies from kube-router will create problems.

**Comment by tiukhtinvladimir** [comment] 2018-02-16 18:55
@murali-reddy thanks for your prompt response. I am using metallb in ARP mode (not BGP). So on a router side I do 1:1 NAT to IP advertising by metallb. Advantage is that metallb control the VIP and move it on node failure.

**Comment by SEJeff** [comment] 2018-02-17 19:04
@tiukhtinvladimir as @murali-reddy mentioned, you can simply add an external ip to the service definition to advertise a vip. If you just want a load balanced service ip, metallb isn't strictly necessary. Also, the arp mode isn't very scalable, per metallb's own docs. The bgp advertised externalip is quite scalable by comparison.

I use this exact same trick to have a highly available vip for my ingress controllers.

**Comment by SEJeff** [comment] 2018-03-21 14:41
@murali-reddy this should be closed as a dupe of #242

**Comment by murali-reddy** [comment] 2018-03-21 19:18
Sure. @tiukhtinvladimir We have some work in-flight (#339) for supporting services of type LoadBalancer. Watch out for #242.

**Closed by murali-reddy** 2018-03-21 19:18 UTC
