### ISSUE TITLE
Network routing controller health check failure during AWS api call

### ISSUE THREAD

**Issue by buddyledungarees** [cloudnativelabs/kube-router#617] opened 2018-12-20 19:56 UTC
As reported in slack room, kube-router pods on nodes that were running the disableSourceDestinationCheck step during startup were failing health checks. Attached is the log from one of those pods.

Upon disabling the health check, the pods were able to successfully complete startup and function normally.

Version: kube-router version v0.2.0, built on 2018-09-01T10:39:18+0530, go1.10

[github-kube-router-health-check-failed.txt](https://github.com/cloudnativelabs/kube-router/files/2700323/github-kube-router-health-check-failed.txt)

**Comment by buddyledungarees** [comment] 2018-12-20 19:57
Relevant aws sdk code:
https://github.com/aws/aws-sdk-go/blob/master/aws/client/default_retryer.go#L33

**Comment by iamakulov** [comment] 2019-08-04 18:19
Just experienced this in production with kube-router v0.1.0 too. In my case, after we restarted master instances, this caused `kube-router` to go to `CrashLoopBackOff`, and worked pods stopped being able to communicate with master.

Increasing the `livenessProbe`’s `initialDelaySeconds` to a higher value (120 seconds, in my case) worked as a workaround, but it’s a pity this happened at all.

**Comment by aauren** [comment] 2020-04-25 05:46
Closing this issue as I believe it to be a duplicate of #407 in the fact that changing the src dst check to affect only a single node, as is proposed would cut down how invasive this procedure is and stop the problem with health checking.

**Closed by aauren** 2020-04-25 05:46 UTC
Labels: bug, help wanted
