### ISSUE TITLE
Provide a command to remove useless route in table 77

### ISSUE THREAD

**Issue by polym** [cloudnativelabs/kube-router#1084] opened 2021-05-17 07:27 UTC
**Is your feature request related to a problem? Please describe.**

After transfering a node with kube-router to a new kubernetes cluster, I found that the route rules in table 77 was not be cleaned up although executed --cleanup-config which was not include ip route rules yet.

AFAIK,  kube-router is watching k8s events which contains node delete event, and when a node is deleted, kube-router will remove releated route rules imedicately. This is great, but on the node which is deleted, how to remove ip route rules and link interface if possible.

**Describe the solution you'd like**

provider a command or put it in sync loop is all good.

1. get node list through apiserver.
2. compare routes, and remove useless rules.

**Describe alternatives you've considered**

1. delete table 77 entirely.
2. remove tun* interface if matched kube-router name regexp.
3. remove kube-bridge and kube-dummy-if.

**Additional context**

**Comment by aauren** [comment] 2021-07-25 04:15
Closing this as a duplicate of #973 - There is a fix in the works for this in #1130

**Closed by aauren** 2021-07-25 04:15 UTC
Labels: feature
