### ISSUE TITLE
Add switch for enabling iptables logging

### ISSUE THREAD

**Issue by whereismyjetpack** [cloudnativelabs/kube-router#359] opened 2018-03-29 11:55 UTC
It would be neat if we could control how kube-router inserts iptables rules. I'd like the ability to inject ` -j log` items on dropped packets for forensics / debugging

**Comment by aauren** [comment] 2020-04-25 03:47
Closing this as duplicate of #505 (I know this one was in first, but the other issue has more information on it)

**Closed by aauren** 2020-04-25 03:47 UTC
Labels: enhancement
