### ISSUE TITLE
" make vagrant-up-single-node " returns fails

### ISSUE THREAD

**Issue by tejaskokje** [cloudnativelabs/kube-router#703] opened 2019-04-03 23:21 UTC
When I try to run `make vagrant-up-single-node`, I am getting following error

`$ make vagrant-up-single-node 
Building for GOARCH=amd64
Everything is gofmt approved!
docker run -v /home/tkokje/godev/src/github.com/cloudnativelabs/kube-router:/go/src/github.com/cloudnativelabs/kube-router -w /go/src/github.com/cloudnativelabs/kube-router golang:1.10.3-alpine \
    sh -c 'go test github.com/cloudnativelabs/kube-router/cmd/kube-router/ github.com/cloudnativelabs/kube-router/pkg/...'
ok  	github.com/cloudnativelabs/kube-router/cmd/kube-router	0.031s
?   	github.com/cloudnativelabs/kube-router/pkg/cmd	[no test files]
ok  	github.com/cloudnativelabs/kube-router/pkg/controllers	0.021s
?   	github.com/cloudnativelabs/kube-router/pkg/controllers/netpol	[no test files]
ok  	github.com/cloudnativelabs/kube-router/pkg/controllers/proxy	0.041s [no tests to run]
ok  	github.com/cloudnativelabs/kube-router/pkg/controllers/routing	2.563s
?   	github.com/cloudnativelabs/kube-router/pkg/healthcheck	[no test files]
?   	github.com/cloudnativelabs/kube-router/pkg/metrics	[no test files]
?   	github.com/cloudnativelabs/kube-router/pkg/options	[no test files]
ok  	github.com/cloudnativelabs/kube-router/pkg/utils	0.030s
Verifying kube-router gobgp for ARCH=x86-64 ...
Starting kube-router container image build.
docker build -t "tejaskokje/kube-router-git:master" -f Dockerfile.amd64.run .
Sending build context to Docker daemon  88.25MB
Step 1/10 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 2/10 : RUN apk add --no-cache       iptables       ip6tables       ipset       iproute2       ipvsadm       conntrack-tools       curl       bash &&     mkdir -p /var/lib/gobgp &&     mkdir -p /usr/local/share/bash-completion &&     curl -L -o /usr/local/share/bash-completion/bash-completion         https://raw.githubusercontent.com/scop/bash-completion/master/bash_completion
 ---> Using cache
 ---> 706001313e5d
Step 3/10 : ADD build/image-assets/bashrc /root/.bashrc
 ---> Using cache
 ---> 432b77435699
Step 4/10 : ADD build/image-assets/profile /root/.profile
 ---> Using cache
 ---> a91989b9dc07
Step 5/10 : ADD build/image-assets/vimrc /root/.vimrc
 ---> Using cache
 ---> 3b9c688d0219
Step 6/10 : ADD build/image-assets/motd-kube-router.sh /etc/motd-kube-router.sh
 ---> Using cache
 ---> e8353b891cfc
Step 7/10 : ADD kube-router gobgp /usr/local/bin/
 ---> Using cache
 ---> b8fdf5f28859
Step 8/10 : RUN cd &&     /usr/local/bin/gobgp --gen-cmpl --bash-cmpl-file /var/lib/gobgp/gobgp-completion.bash
 ---> Using cache
 ---> a07addf84373
Step 9/10 : WORKDIR "/root"
 ---> Using cache
 ---> 1080981e1d02
Step 10/10 : ENTRYPOINT ["/usr/local/bin/kube-router"]
 ---> Using cache
 ---> 7e89f215488e
Successfully built 7e89f215488e
Successfully tagged tejaskokje/kube-router-git:master
Finished kube-router container image build.
INFO: Bootkube repo not found. Nothing to destroy.
INFO: Bootkube repo not found.
INFO: Cloning bootkube version v0.6.0_kube-router.
Cloning into '/home/tkokje/godev/src/github.com/cloudnativelabs/kube-router/hack/_cache/bootkube'...
remote: Enumerating objects: 4502, done.
remote: Counting objects: 100% (4502/4502), done.
remote: Compressing objects: 100% (3214/3214), done.
remote: Total 4502 (delta 1420), reused 2870 (delta 1112), pack-reused 0
Receiving objects: 100% (4502/4502), 5.87 MiB | 11.61 MiB/s, done.
Resolving deltas: 100% (1420/1420), done.
Checking connectivity... done.
Note: checking out 'ef47c632a7fbf0bdceec82e49b7029af230f5a67'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

INFO: Exporting your kube-router container image.
INFO: Caching hyperkube images to Bootkube local-images directory.
WARN: rkt not found. Skipping rkt ACI image caching.
INFO: Fetching quay.io/coreos/hyperkube:v1.7.1_coreos.0 Docker image.
v1.7.1_coreos.0: Pulling from coreos/hyperkube
3ebc4e3ed1b2: Already exists 
b80dad216ca4: Already exists 
abb3db75eedf: Already exists 
1871977ec4b7: Already exists 
26e3f6feceed: Already exists 
3960cf27756a: Already exists 
Digest: sha256:cc57bd170e562ab699b6dd2244f2683018214c8228591dc641cffce0f0f92037
Status: Image is up to date for quay.io/coreos/hyperkube:v1.7.1_coreos.0
INFO: Saving quay.io/coreos/hyperkube:v1.7.1_coreos.0 Docker image to cache directory.
INFO: Using custom manifests from /home/tkokje/godev/src/github.com/cloudnativelabs/kube-router/contrib/bootkube
cp: cannot stat '/home/tkokje/godev/src/github.com/cloudnativelabs/kube-router/contrib/bootkube/*.yml': No such file or directory
INFO: No custom .yml files found.
Modifying image attribute in /home/tkokje/godev/src/github.com/cloudnativelabs/kube-router/hack/_cache/bootkube/hack/custom-manifests/kube-router.yaml
Verify modification:
        image: test.kube-router.io
        image: busybox
        imagePullPolicy: IfNotPresent
        imagePullPolicy: IfNotPresent
INFO: Building Bootkube
make[1]: Entering directory '/home/tkokje/godev/src/github.com/cloudnativelabs/kube-router/hack/_cache/bootkube'
mkdir -p _output/bin/linux/
GOOS=linux go build  -ldflags "-X github.com/kubernetes-incubator/bootkube/pkg/version.Version=v0.6.0_kube-router" -o _output/bin/linux/bootkube github.com/kubernetes-incubator/bootkube/cmd/bootkube
mkdir -p _output/bin/darwin/
GOOS=darwin go build  -ldflags "-X github.com/kubernetes-incubator/bootkube/pkg/version.Version=v0.6.0_kube-router" -o _output/bin/darwin/bootkube github.com/kubernetes-incubator/bootkube/cmd/bootkube
mkdir -p _output/bin/linux/
GOOS=linux go build  -ldflags "-X github.com/kubernetes-incubator/bootkube/pkg/version.Version=v0.6.0_kube-router" -o _output/bin/linux/checkpoint github.com/kubernetes-incubator/bootkube/cmd/checkpoint
make[1]: Leaving directory '/home/tkokje/godev/src/github.com/cloudnativelabs/kube-router/hack/_cache/bootkube'
INFO: Starting VM(s) and cluster
Writing asset: cluster/manifests/kube-scheduler.yaml
Writing asset: cluster/manifests/kube-scheduler-disruption.yaml
Writing asset: cluster/manifests/kube-controller-manager-disruption.yaml
Writing asset: cluster/manifests/coredns-cluster-role-binding.yaml
Writing asset: cluster/manifests/coredns-cluster-role.yaml
Writing asset: cluster/manifests/coredns-deployment.yaml
Writing asset: cluster/manifests/coredns-service-account.yaml
Writing asset: cluster/manifests/pod-checkpointer.yaml
Writing asset: cluster/manifests/pod-checkpointer-sa.yaml
Writing asset: cluster/manifests/pod-checkpointer-role.yaml
Writing asset: cluster/manifests/pod-checkpointer-role-binding.yaml
Writing asset: cluster/manifests/csr-approver-role-binding.yaml
Writing asset: cluster/manifests/csr-bootstrap-role-binding.yaml
Writing asset: cluster/manifests/csr-renewal-role-binding.yaml
Writing asset: cluster/manifests/kube-system-rbac-role-binding.yaml
Writing asset: cluster/manifests/kube-controller-manager.yaml
Writing asset: cluster/manifests/kube-controller-manager-service-account.yaml
Writing asset: cluster/manifests/kube-controller-manager-role-binding.yaml
Writing asset: cluster/manifests/kube-apiserver.yaml
Writing asset: cluster/manifests/kube-proxy.yaml
Writing asset: cluster/manifests/kube-proxy-sa.yaml
Writing asset: cluster/manifests/kube-proxy-role-binding.yaml
Writing asset: cluster/manifests/coredns-config.yaml
Writing asset: cluster/manifests/coredns-service.yaml
Writing asset: cluster/bootstrap-manifests/bootstrap-apiserver.yaml
Writing asset: cluster/bootstrap-manifests/bootstrap-controller-manager.yaml
Writing asset: cluster/bootstrap-manifests/bootstrap-scheduler.yaml
Writing asset: cluster/manifests/flannel.yaml
Writing asset: cluster/manifests/flannel-cfg.yaml
Writing asset: cluster/manifests/flannel-cluster-role.yaml
Writing asset: cluster/manifests/flannel-cluster-role-binding.yaml
Writing asset: cluster/manifests/flannel-sa.yaml
Writing asset: cluster/tls/ca.key
Writing asset: cluster/tls/ca.crt
Writing asset: cluster/tls/apiserver.key
Writing asset: cluster/tls/apiserver.crt
Writing asset: cluster/tls/service-account.key
Writing asset: cluster/tls/service-account.pub
Writing asset: cluster/tls/admin.key
Writing asset: cluster/tls/admin.crt
Writing asset: cluster/tls/etcd/peer-ca.crt
Writing asset: cluster/tls/etcd/peer.key
Writing asset: cluster/tls/etcd/peer.crt
Writing asset: cluster/tls/etcd/server-ca.crt
Writing asset: cluster/tls/etcd/server.key
Writing asset: cluster/tls/etcd/server.crt
Writing asset: cluster/tls/etcd-client-ca.crt
Writing asset: cluster/tls/etcd-client.key
Writing asset: cluster/tls/etcd-client.crt
Writing asset: cluster/auth/kubeconfig
Writing asset: cluster/manifests/kubeconfig-in-cluster.yaml
Writing asset: cluster/auth/kubeconfig-kubelet
Writing asset: cluster/manifests/kubelet-bootstrap-token.yaml
Writing asset: cluster/manifests/kube-apiserver-secret.yaml
Writing asset: cluster/manifests/kube-controller-manager-secret.yaml
rm: cannot remove 'cluster/manifests/kube-flannel.yaml': No such file or directory
rm: cannot remove 'cluster/manifests/kube-flannel-cfg.yaml': No such file or directory
Makefile:64: recipe for target 'vagrant-up' failed
make: *** [vagrant-up] Error 1
`

**Comment by tejaskokje** [comment] 2019-04-03 23:26
I am running it on Linux Mint 18.3 with `BUILD_IN_DOCKER` set to true in `Makefile`
I am not sure where this `Writing asset` is coming from. When I ran `bootkube-up` manually, I didn't see errors

`src/github.com/cloudnativelabs/kube-router/hack/_cache/bootkube/hack/single-node $ ./bootkube-up 
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'coreos-stable'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'coreos-stable' is up to date...
==> default: Setting the name of the VM: single-node_default_1554333869349_43056
==> default: Fixed port collision for 22 => 2222. Now on port 2203.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2203 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2203
    default: SSH username: core
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/tkokje/godev/src/github.com/cloudnativelabs/kube-router/hack/_cache/bootkube/hack/local-images/ => /var/tmp/images
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20190403-26515-bot9v3.sh
==> default: ls: 
==> default: cannot access '/var/tmp/images/*.aci'
==> default: : No such file or directory
==> default: No .aci images found in /var/tmp/images
==> default: Importing /var/tmp/images/hyperkube-v1.7.1_coreos.0.docker
==> default: Loaded image: quay.io/coreos/hyperkube:v1.7.1_coreos.0
==> default: Importing /var/tmp/images/kube-router.docker
==> default: Loaded image: test.kube-router.io:latest
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20190403-26515-19kskii.sh
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
Starting temporary bootstrap control plane...
Waiting for api-server...
`

**Comment by aauren** [comment] 2019-04-26 00:42
For what it's worth, I also get this same error under Gentoo:

```
BUILD_IN_DOCKER=true make vagrant-up-single-node                                                                                                                                                                                                                                                                                                              
Building for GOARCH=amd64                                                                                                      
Everything is gofmt approved!                                                                                                                                                                                                                                  
docker run -v /home/auren/go-workspace/src/github.com/cloudnativelabs/kube-router:/go/src/github.com/cloudnativelabs/kube-router -w /go/src/github.com/cloudnativelabs/kube-router golang:1.10.8-alpine3.9 \                                                   
    sh -c 'go test -v -timeout 30s github.com/cloudnativelabs/kube-router/cmd/kube-router/ github.com/cloudnativelabs/kube-router/pkg/...'                                                                                                                     
=== RUN   TestMainHelp                                                                                                                                                                                                                                         
--- PASS: TestMainHelp (0.00s)                                                                                                                                                                                                                                 
PASS                                                                                                                                                                                                                                                           
ok      github.com/cloudnativelabs/kube-router/cmd/kube-router  0.073s                                                                                                                                                                                         
?       github.com/cloudnativelabs/kube-router/pkg/cmd  [no test files]                                                                                                                                                                                        
=== RUN   TestControllers                                                                                                                                                                                                                                      
Running Suite: Controllers Suite                                                                                                                                                                                                                               
================================                                                                                                                                                                                                                               
Random Seed: 1556238555                                                                                                                                                                                                                                        
Will run 0 of 0 specs                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
Ran 0 of 0 Specs in 0.000 seconds                                                                                                                                                                                                                              
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped --- PASS: TestControllers (0.00s)

... (output reduced for brevity)

Writing asset: cluster/tls/etcd/server.crt
Writing asset: cluster/tls/etcd-client-ca.crt
Writing asset: cluster/tls/etcd-client.key
Writing asset: cluster/tls/etcd-client.crt
Writing asset: cluster/auth/kubeconfig
Writing asset: cluster/manifests/kubeconfig-in-cluster.yaml
Writing asset: cluster/auth/kubeconfig-kubelet
Writing asset: cluster/manifests/kubelet-bootstrap-token.yaml
Writing asset: cluster/manifests/kube-apiserver-secret.yaml
Writing asset: cluster/manifests/kube-controller-manager-secret.yaml
rm: cannot remove 'cluster/manifests/kube-flannel.yaml': No such file or directory
rm: cannot remove 'cluster/manifests/kube-flannel-cfg.yaml': No such file or directory
make: *** [Makefile:64: vagrant-up] Error 1
```

**Comment by cloudnativer** [comment] 2020-07-10 08:28
Can you try to see if the file `cluster/manifests/kube-flannel.yaml` exists? Is `cluster/manifests/kube-flannel.yaml` written in the code or configuration of some place?

**Comment by aauren** [comment] 2020-07-13 17:53
It looks like the problem is that this is pulling from an outside repo that was configured according to a old kube-router repo configuration: https://github.com/bzub/bootkube/blob/v0.6.0_kube-router/hack/single-node/bootkube-up#L38

It's likely that this entire process of using Vagrant will need to be updated to avoid the reliance on an outside, user-controlled repository.

**Comment by murali-reddy** [comment] 2020-07-14 04:41
It was effort done very early (as an attempt to run tests in CI) which was never used. Probably we should clean up all the Vagrant code. Closing the issue.

**Closed by murali-reddy** 2020-07-14 04:41 UTC
Labels: bug, help wanted, verified
