### ISSUE TITLE
Hardcoded grpcServer port and non-configurable grpcServer flag

### ISSUE THREAD

**Issue by zigurdsbevalds** [cloudnativelabs/kube-router#1762] opened 2024-11-12 16:05 UTC
https://github.com/cloudnativelabs/kube-router/blob/bd63093e8c447833af3c3f568a8f64f77072b335/pkg/controllers/routing/network_routes_controller.go#L1010

It would be nice to have KubeRouterConfig.BGPGrpcPort instead of hardcoding 50051 (which could just be default).
And allow to disable it grpc : KubeRouterConfig.BGPGrpcEnabled with default as true.

**Comment by aauren** [comment] 2024-11-12 18:16
Can you please fill out the entire issue template? There is a lot missing on this issue that would help prioritize it or make it actionable.

What is the impetus behind this change? How does it make kube-router better? Was there a specific problem caused by using this port? Or exposing the port at all?

We are generally very judicious with how many flags we expose, so for this to be considered it would need to make a strong case for why this would be a feature that many people would value or find useful.

I'm closing this issue for now, but please feel free to open another issue that uses the pre-defined templates and better advocates for this if it is something that is important to you.

**Closed by aauren** 2024-11-12 18:16 UTC
