### ISSUE TITLE
Failed to create network policy controller

### ISSUE THREAD

**Issue by elvizlai** [cloudnativelabs/kube-router#699] opened 2019-04-01 08:55 UTC
bare run kuber-router failed.
```
[root@k8s-gw ~]# ./kube-router --master=http://10.140.0.2:8080 --run-router=true --run-firewall=true --run-service-proxy=true --hostname-override=10.140.0.4
I0401 08:53:14.419246   17516 kube-router.go:207] Running ./kube-router version , built on , go1.11.4
Failed to run kube-router: Failed to create network policy controller: Failed to identify the node by NODE_NAME, hostname or --hostname-override
```

kernel
```
[root@k8s-gw ~]# uname -r
4.4.177-1.el7.elrepo.x86_64
```

sysctl
```
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
```

host `k8s-gw` is not node of k8s cluster, the log -v=8 shows
```
I0401 09:05:28.145005   17806 round_trippers.go:414] GET http://10.140.0.2:8080/api/v1/nodes/k8s-gw
I0401 09:05:28.145014   17806 round_trippers.go:421] Request Headers:
I0401 09:05:28.145019   17806 round_trippers.go:424]     Accept: application/json, */*
I0401 09:05:28.145026   17806 round_trippers.go:424]     User-Agent: kube-router/v0.0.0 (linux/amd64) kubernetes/$Format
I0401 09:05:28.148828   17806 round_trippers.go:439] Response Status: 404 Not Found in 3 milliseconds
I0401 09:05:28.148874   17806 round_trippers.go:442] Response Headers:
I0401 09:05:28.148879   17806 round_trippers.go:445]     Content-Type: application/json
I0401 09:05:28.148884   17806 round_trippers.go:445]     Date: Mon, 01 Apr 2019 09:05:28 GMT
I0401 09:05:28.148887   17806 round_trippers.go:445]     Content-Length: 182
I0401 09:05:28.148933   17806 request.go:836] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"nodes \"k8s-gw\" not found","reason":"NotFound","details":{"name":"k8s-gw","kind":"nodes"},"code":404}
I0401 09:05:28.149292   17806 round_trippers.go:414] GET http://10.140.0.2:8080/api/v1/nodes/10.140.0.4
I0401 09:05:28.149305   17806 round_trippers.go:421] Request Headers:
I0401 09:05:28.149310   17806 round_trippers.go:424]     Accept: application/json, */*
I0401 09:05:28.149314   17806 round_trippers.go:424]     User-Agent: kube-router/v0.0.0 (linux/amd64) kubernetes/$Format
I0401 09:05:28.151790   17806 round_trippers.go:439] Response Status: 404 Not Found in 2 milliseconds
I0401 09:05:28.151814   17806 round_trippers.go:442] Response Headers:
I0401 09:05:28.151819   17806 round_trippers.go:445]     Content-Length: 190
I0401 09:05:28.151822   17806 round_trippers.go:445]     Content-Type: application/json
I0401 09:05:28.151826   17806 round_trippers.go:445]     Date: Mon, 01 Apr 2019 09:05:28 GMT
I0401 09:05:28.151870   17806 request.go:836] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"nodes \"10.140.0.4\" not found","reason":"NotFound","details":{"name":"10.140.0.4","kind":"nodes"},"code":404}
Failed to run kube-router: Failed to create network routing controller: Failed getting node object from API server: Failed to identify the node by NODE_NAME, hostname or --hostname-override
```

So is there any way to run kube-router without deploy as node?

**Comment by murali-reddy** [comment] 2019-04-02 04:09
@elvizlai its implicitly assumed that node on which kube-router is a Kubernetes node. Is there a use-case or reason you want to run kube-router on Kubernetes node?

**Comment by elvizlai** [comment] 2019-04-03 02:44
@murali-reddy yes, we have some vps in same vpc with k8s as gateway. They need communicate with xxx.ns.svc.cluster.local directly.

**Comment by aauren** [comment] 2020-04-25 06:57
Closing as duplicate of #552

**Closed by aauren** 2020-04-25 06:57 UTC
