### ISSUE TITLE
Prevent UnauthorizedApiCalls from disableSourceDestinationCheck

### ISSUE THREAD

**Issue by xanonid** [cloudnativelabs/kube-router#615] opened 2018-12-18 12:29 UTC
Wishlist issue:

Currently, kube-router tries to disable the source-destination-check by default from all nodes and if unauthorized, stop it with a log notice. This works flawless, but the unpleasant thing are the unauthorized API calls: It is best practise, to have alerts on those (cf. e.g. [this recommendation](https://www.cloudconformity.com/conformity-rules/CloudWatchLogs/authorization-failures-alarm.html)), therefore each kube-router start/restart triggers an alert if the nodes does not have the corresponding IAM permissions which is needed to prevent RateLimiting issues.

It would be nice, if there is a flag/annotation, which allows to disable `disableSourceDestinationCheck` on nodes at all such that they do not perform any unauthorized API call.

**Comment by mk01** [comment] 2018-12-24 15:52
there is 77459ddb2c665552900a975a8ddda6d8241d372b which is introducing this functionality... isn't it what you are looking for ?

**Comment by xanonid** [comment] 2019-01-21 11:12
@mk01 Thanks for the hint, the `--disable-source-dest-check` flag is helpful.

Still the situation is not optimal, as the usage of the flag prevents the usage of the same daemonset for master and nodes (without adding logic that sets flags at runtime or disabling the src-dest-check by a third-party solution).

IMHO, there should be a mode added, where kube-router simply disables the src-dest-check only for the instance it is running on and does not care for other nodes.

**Comment by aauren** [comment] 2020-04-25 05:39
Work around provided. Additional idea is a good one, but is a duplicate of #407. Closing as duplicate.

**Closed by aauren** 2020-04-25 05:39 UTC
Labels: enhancement, help wanted
