### ISSUE TITLE
Memory overuse

### ISSUE THREAD

**Issue by Onlinehead** [cloudnativelabs/kube-router#795] opened 2019-10-13 12:13 UTC
Hello,
I have an installation of 12 K8s hosts (3 masters + 9 nodes) with Kube-router as a CNI and proxy replacement.
For some of nodes, I see memory over usage which increasing in time, so it looks like as a memory leak. 
I enable `pprof` and waited for some time to get a reproduce the situation.
I got one of pods where the problem reproduced and investigate its behavior a bit.
CPU usage of kube-router on all nodes are pretty high, but acceptable for my configuration.

**Container version:** ` cloudnativelabs/kube-router@sha256:12459f482a57f496737378921dcc57a50bbf414acaf92d31a46513ef5c116c92`
**Uptime:** `10 days.`
**Base OS:** CentOS 7, `3.10.0-957.27.2.el7.x86_64`
**K8s**: `v1.14.6`
**Current memory usage** (_based on `container_memory_working_set_bytes` metric_): 3.868 Gb
**CLI flags:**  `--run-router=true --run-firewall=true --run-service-proxy=true --enable-pprof --kubeconfig=/var/lib/kube-router/kubeconfig`
**Memory top by pperf:**
```
(pprof) top
Showing nodes accounting for 1634.22MB, 98.19% of 1664.32MB total
Dropped 114 nodes (cum <= 8.32MB)
Showing top 10 nodes out of 49
      flat  flat%   sum%        cum   cum%
  519.14MB 31.19% 31.19%   519.14MB 31.19%  runtime.convT2Enoptr
  391.01MB 23.49% 54.69%   518.04MB 31.13%  github.com/cloudnativelabs/kube-router/vendor/k8s.io/api/core/v1.(*NodeSelectorTerm).DeepCopyInto
  339.59MB 20.40% 75.09%   339.59MB 20.40%  runtime.growWork_fast32
  127.03MB  7.63% 82.72%   127.03MB  7.63%  github.com/cloudnativelabs/kube-router/vendor/k8s.io/api/core/v1.(*NodeSpec).DeepCopyInto
  106.06MB  6.37% 89.10%   106.06MB  6.37%  runtime.evacuate_fast32
   94.50MB  5.68% 94.77%    94.50MB  5.68%  runtime.convT32
   35.50MB  2.13% 96.91%    35.50MB  2.13%  github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1.(*thirdPartyResources).Patch
   21.38MB  1.28% 98.19%    21.38MB  1.28%  github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/kubernetes/typed/networking/v1.(*networkPolicies).Watch
         0     0% 98.19%   339.59MB 20.40%  github.com/cloudnativelabs/kube-router/vendor/github.com/googleapis/gnostic/OpenAPIv2.(*Document).ToRawInfo
         0     0% 98.19%  1574.29MB 94.59%  github.com/cloudnativelabs/kube-router/vendor/github.com/googleapis/gnostic/OpenAPIv2.(*NamedSchema).ResolveReferences
```
**Memory usage visualization:**
![out](https://user-images.githubusercontent.com/1026551/66715284-ed774b00-edc1-11e9-8e69-989034e34fbc.png)
**Memory allocation from the beginning visualization:**
![out_alloc](https://user-images.githubusercontent.com/1026551/66715296-20b9da00-edc2-11e9-88f3-a20e9ee8f86e.png)
**CPU usage visualization:**
![out_cpu](https://user-images.githubusercontent.com/1026551/66715313-4a730100-edc2-11e9-996f-809b858d4f9f.png)
In attachment, you can also find a heam_dumps.zip, which contains 2 heap dumped with 30s waiting between them:
[heap_dumps.zip](https://github.com/cloudnativelabs/kube-router/files/3721705/heap_dumps.zip)

**Comment by andrewsykim** [comment] 2019-10-22 23:13
@Onlinehead thank you for doing this, I'll try to take a look soon

**Comment by salanki** [comment] 2020-05-01 07:03
I am seeing basically unbounded memory growth. This seems to be correlated with number of pods cycled (created/deleted) **in the cluster**. It seems as some resource is not freed up even after a Pod is deleted. This happens on all nodes, not only the nodes where said Pods are created.

![Screen Shot 2020-05-01 at 02 59 35](https://user-images.githubusercontent.com/192223/80788710-da5a7b80-8b57-11ea-9744-c96c9effc5f3.png)

I put a limit to 2G of memory for my `kube-router` at the end of the graph, so it is getting OOM killed all the time. Not good.

Is this the same as you are seeing?

**Comment by murali-reddy** [comment] 2020-05-01 13:54
@salanki I am looking at this issue to understnad the behaviour. Would be able take and share  pprof heap profile?

**Comment by rmb938** [comment] 2020-05-04 18:39
I am seeing the same issue on my larger clusters ~200 nodes. My smaller clusters 10-15 nodes don't seem to have this issue, probably because network policies aren't used as much on them.

Here is a graph of a kube-router pod that has been online for a little more than 30 days... almost 35 gb of ram.

<img width="1417" alt="Screen Shot 2020-05-04 at 10 45 04 AM" src="https://user-images.githubusercontent.com/544545/80996540-942a4400-8e05-11ea-982b-c9824dbc2f39.png">

After restarting all the kube-router pods they are now around 200-500mb of memory. It does seem like it is slowly increasing though. Here is  a graph from the last hour after the restart.

<img width="1404" alt="Screen Shot 2020-05-04 at 1 38 33 PM" src="https://user-images.githubusercontent.com/544545/81000953-9348e080-8e0c-11ea-9f04-8fc0f3be0708.png">


I am using the following prometheus query

```
container_memory_working_set_bytes{namespace="kube-system", pod=~"kube-router-.*", container="kube-router"}
``` 

I can get a pprof heap profile sometime this week.

**Comment by salanki** [comment] 2020-05-04 19:55
I have 300 nodes in my cluster. When removing some network policies, it seems to have slowed down a bit, but still happening.

**Comment by SerialVelocity** [comment] 2020-05-07 10:32
I might have the same issue. For me at least, I have a large amount of `KUBE-POD-FW-*` and `KUBE-NWPLCY-*` rules being generated that shouldn't be there:
```
-A KUBE-NWPLCY-JETO5HCCICPORJFD -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name mysql namespace other" -m set --match-set KUBE-SRC-RKCNJAY4ZMHT3ECQ src -m set --match-set KUBE-DST-VAWT2357PZRYVGDI dst -m tcp --dport 3306 -j ACCEPT
-A KUBE-NWPLCY-JMA3X7HLSBOHV3YX -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name mysql namespace other" -m set --match-set KUBE-SRC-RKCNJAY4ZMHT3ECQ src -m set --match-set KUBE-DST-VAWT2357PZRYVGDI dst -m tcp --dport 3306 -j ACCEPT
-A KUBE-NWPLCY-K6U2HGLSIC4TKVPJ -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name mysql namespace other" -m set --match-set KUBE-SRC-RKCNJAY4ZMHT3ECQ src -m set --match-set KUBE-DST-VAWT2357PZRYVGDI dst -m tcp --dport 3306 -j ACCEPT
-A KUBE-NWPLCY-KVM3JJIFA3NGXEWT -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name mysql namespace other" -m set --match-set KUBE-SRC-RKCNJAY4ZMHT3ECQ src -m set --match-set KUBE-DST-VAWT2357PZRYVGDI dst -m tcp --dport 3306 -j ACCEPT
-A KUBE-NWPLCY-KWBSGSZXTYUTZETX -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name mysql namespace other" -m set --match-set KUBE-SRC-RKCNJAY4ZMHT3ECQ src -m set --match-set KUBE-DST-VAWT2357PZRYVGDI dst -m tcp --dport 3306 -j ACCEPT
-A KUBE-NWPLCY-KYO7N7MAAFNMMDPD -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name mysql namespace other" -m set --match-set KUBE-SRC-RKCNJAY4ZMHT3ECQ src -m set --match-set KUBE-DST-VAWT2357PZRYVGDI dst -m tcp --dport 3306 -j ACCEPT
-A KUBE-NWPLCY-L3ZJ76FS4H34WKAT -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to dest pods selected by policy name mysql namespace other" -m set --match-set KUBE-SRC-RKCNJAY4ZMHT3ECQ src -m set --match-set KUBE-DST-VAWT2357PZRYVGDI dst -m tcp --dport 3306 -j ACCEPT
```

**Comment by murali-reddy** [comment] 2020-05-07 11:45
@SerialVelocity Can you please open a seperate issue, if possible with details of network policies applied and dump of iptables-save? Also please share the kube-router version you are using. There is cleanup code which deletes stale iptable chains if they are not in use. So not sure what is happening in your setup. Please share kube-router logs as well.

**Comment by salanki** [comment] 2020-05-07 14:31
My case seems to be related to Firewall too. When I disable firewall, memory usage is constant.

**Comment by aauren** [comment] 2020-05-16 16:09
Just wanted to update this thread. We're still working on trying to figure out what's happening here. It's made more difficult by some people on the team being able to reproduce it and others not. For instance, at least with the cluster I operate, disabling firewall doesn't seem to have any affect on the issue. It's possible that there might be multiple problems here.

We'll keep hunting for it. In the meantime, if anyone else has any other light to shed on this issue, please continue to add comments. Any help here is appreciated as this is one of the last outstanding issues for a 1.0.0 stable release which we are trying for before looking to additional feature or design change PRs.

**Comment by aauren** [comment] 2020-05-20 19:17
Now that #902 has been merged, this should be resolved with the release of https://github.com/cloudnativelabs/kube-router/releases/tag/v1.0.0-rc4

**Closed by aauren** 2020-05-20 19:17 UTC
Labels: p2, performance

**Comment by salanki** [comment] 2020-05-20 19:31
@aauren both mine and OPs issues are on 0.4.0. Did the #902 issue exist in 0.4.0 as well? As I read it it was a 1.0.0 thing only?

**Comment by aauren** [comment] 2020-05-21 00:59
Yes, I would be willing to guess that this issue goes back since the beginning of the controller. But it definitely existed in 0.4.0. It has to do with the controller being run inside a single go routine and the mounting set of time it takes to write all of the network policies to iptables as the cluster state begins to change.

I will say that my pprof visualization looked a little different than the OPs. However, I believe the memory issue that we were able to reproduce is identical to the one you were struggling with given that they both related to the network_policy_controller exclusively.

Anyway, give 1.0.0-rc4 a shot and let us know if you hit the same issue again when you enable the network_policy_controller. I've had it running for a few days now under significant load without any significant gains.
