### ISSUE TITLE
kube-router firewall doesn't reject traffic in dsr mode

### ISSUE THREAD

**Issue by dontreboot** [cloudnativelabs/kube-router#683] opened 2019-02-28 02:07 UTC
I have this network policy to only allow local traffic on port 80 and 443; however, from my test all the traffic to pod is going through.
```apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-whitelist-prod-1
  namespace: ingress-controller
spec:
  podSelector:
    matchLabels:
      run: haproxy-ingress-prod-1
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
```
kube router announces an anycast IP (dsr tunneling mode) and ipvs has rule to route traffic to pod 10.254.1.178 and here are current iptables rules:
```Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination
1    KUBE-ROUTER-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* handle traffic to IPVS service IPs in custom chain */ match-set kube-router-service-ips dst
2    KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy DROP)
num  target     prot opt source               destination
1    KUBE-POD-FW-CWP3Q55X3ZOLYGTR  all  --  0.0.0.0/0            10.254.1.178         PHYSDEV match --physdev-is-bridged /* rule to jump traffic destined to POD name:haproxy-ingress-prod-1-59b57c76f-w55w4 namespace: ingress-controller to chain KUBE-POD-FW-CWP3Q55X3ZOLYGTR */
2    KUBE-POD-FW-CWP3Q55X3ZOLYGTR  all  --  0.0.0.0/0            10.254.1.178         /* rule to jump traffic destined to POD name:haproxy-ingress-prod-1-59b57c76f-w55w4 namespace: ingress-controller to chain KUBE-POD-FW-CWP3Q55X3ZOLYGTR */
3    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* allow outbound node port traffic on node interface with which node ip is associated */
4    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* allow inbound traffic to pods */
5    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* allow outbound traffic from pods */
6    DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0
7    DOCKER-ISOLATION-STAGE-1  all  --  0.0.0.0/0            0.0.0.0/0
8    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
9    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
10   ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
11   ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination
1    KUBE-POD-FW-CWP3Q55X3ZOLYGTR  all  --  0.0.0.0/0            10.254.1.178         /* rule to jump traffic destined to POD name:haproxy-ingress-prod-1-59b57c76f-w55w4 namespace: ingress-controller to chain KUBE-POD-FW-CWP3Q55X3ZOLYGTR */
2    KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER (1 references)
num  target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
num  target     prot opt source               destination
1    DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
2    RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
num  target     prot opt source               destination
1    DROP       all  --  0.0.0.0/0            0.0.0.0/0
2    RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
num  target     prot opt source               destination
1    RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain KUBE-FIREWALL (2 references)
num  target     prot opt source               destination
1    DROP       all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-NWPLCY-ZETSNECQDFVUZ5CH (1 references)
num  target     prot opt source               destination
1    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            /* rule to ACCEPT traffic from specified ipBlocks to dest pods selected by policy name: ingress-whitelist-prod-1 namespace ingress-controller */ match-set KUBE-SRC-PXSWRFYP2MNO2NWY src match-set KUBE-DST-RIHTLKYD2RUKKK5B dst tcp dpt:80
2    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            /* rule to ACCEPT traffic from specified ipBlocks to dest pods selected by policy name: ingress-whitelist-prod-1 namespace ingress-controller */ match-set KUBE-SRC-PXSWRFYP2MNO2NWY src match-set KUBE-DST-RIHTLKYD2RUKKK5B dst tcp dpt:443

Chain KUBE-POD-FW-CWP3Q55X3ZOLYGTR (3 references)
num  target     prot opt source               destination
1    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* rule for stateful firewall for pod */ ctstate RELATED,ESTABLISHED
2    ACCEPT     all  --  0.0.0.0/0            10.254.1.178         /* rule to permit the traffic traffic to pods when source is the pod's local node */ ADDRTYPE match src-type LOCAL
3    KUBE-NWPLCY-ZETSNECQDFVUZ5CH  all  --  0.0.0.0/0            0.0.0.0/0            /* run through nw policy ingress-whitelist-prod-1 */
4    REJECT     all  --  0.0.0.0/0            0.0.0.0/0            /* default rule to REJECT traffic destined for POD name:haproxy-ingress-prod-1-59b57c76f-w55w4 namespace: ingress-controller */ reject-with icmp-port-unreachable

Chain KUBE-ROUTER-SERVICES (1 references)
num  target     prot opt source               destination
1    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* allow input traffic to ipvs services */ match-set kube-router-ipvs-services dst,dst
2    ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            /* allow icmp echo requests to service IPs */ icmptype 8
3    REJECT     all  --  0.0.0.0/0            0.0.0.0/0            /* reject all unexpected traffic to service IPs */ ! match-set kube-router-local-ips dst reject-with icmp-port-unreachable
```

My understanding is that rule 1 and 2 from the FORWARD chain matched first then iptables checks chain KUBE-POD-FW-CWP3Q55X3ZOLYGTR. rule 1 from that chain doesn't match so it goes to rule 2 which I think it may be a match for some reasons because if that's not case, rule 4 will kick in and my connection should get rejected.  For traffic destined for a DSR IP, will rule 2 kick in and allow all traffic?

**Comment by aauren** [comment] 2020-04-25 06:38
Thanks for reporting this! It's definitely something that we hope to follow up with soon. For now closing this issue as a duplicate of #570

**Closed by aauren** 2020-04-25 06:38 UTC
