### ISSUE TITLE
Missing heartbeat when disabling src/dest check

### ISSUE THREAD

**Issue by renaudhager** [cloudnativelabs/kube-router#853] opened 2020-03-05 17:35 UTC
Hi all,

It looks like there is the same kind of issue when kube-router update the src/dest check attribut ( on AWS) than here https://github.com/cloudnativelabs/kube-router/issues/725.
On my cluster which has ~15 nodes, kube router enter in a crash loop when it starts while it tries to disable src/dest check.

Here the logs:

```
I0206 15:44:27.453704       1 network_policy_controller.go:142] Starting network policy controller
I0206 15:44:27.466604       1 network_routes_controller.go:983] Could not find annotation `kube-router.io/bgp-local-addresses` on node object so BGP will listen on node IP: 10.50.1.201 address.
I0206 15:44:27.479837       1 network_services_controller.go:284] Starting network services controller
I0206 15:44:28.037699       1 aws.go:63] Disabled source destination check for the instance: i-076f7fe85a84b87ad
I0206 15:44:29.284469       1 aws.go:63] Disabled source destination check for the instance: i-01d773ec85e47d2b9
I0206 15:44:30.557509       1 aws.go:63] Disabled source destination check for the instance: i-0b04c82554ec39800
I0206 15:44:31.829163       1 aws.go:63] Disabled source destination check for the instance: i-0de5636bd8c4c1384
I0206 15:44:33.053620       1 aws.go:63] Disabled source destination check for the instance: i-097a3f879a682a376
I0206 15:44:34.337309       1 aws.go:63] Disabled source destination check for the instance: i-03d4057fd34222152
I0206 15:44:35.651659       1 aws.go:63] Disabled source destination check for the instance: i-0d9ea2afa3897d5f8
I0206 15:44:36.960242       1 aws.go:63] Disabled source destination check for the instance: i-00088a224f9cfd991
E0206 15:44:37.427434       1 health_controller.go:118] Network Routing Controller heartbeat missed
I0206 15:44:38.214183       1 aws.go:63] Disabled source destination check for the instance: i-0149d40f1ab884f8f
I0206 15:44:39.565684       1 aws.go:63] Disabled source destination check for the instance: i-053707dae3b88dac6
I0206 15:44:40.844416       1 aws.go:63] Disabled source destination check for the instance: i-0ef0a1dfbeba59b31
I0206 15:44:42.115857       1 aws.go:63] Disabled source destination check for the instance: i-0b2360766d7e68d1f
E0206 15:44:42.427429       1 health_controller.go:118] Network Routing Controller heartbeat missed
I0206 15:44:43.401684       1 aws.go:63] Disabled source destination check for the instance: i-03bff8563032c37a7
I0206 15:44:44.279128       1 kube-router.go:178] Shutting down the controllers
I0206 15:44:44.279176       1 health_controller.go:161] Shutting down health controller
E0206 15:44:44.279240       1 health_controller.go:150] Health controller error: http: Server closed
I0206 15:44:44.279571       1 network_services_controller.go:358] Shutting down network services controller
I0206 15:44:44.279592       1 health_controller.go:178] Shutting down HealthController RunCheck
I0206 15:44:44.279698       1 network_policy_controller.go:164] Shutting down network policies controller
I0206 15:44:44.659446       1 aws.go:63] Disabled source destination check for the instance: i-06ebf496c7d187008
I0206 15:44:45.974314       1 aws.go:63] Disabled source destination check for the instance: i-0ed3395628c4cf902
I0206 15:44:46.989718       1 network_routes_controller.go:223] Starting network route controller
I0206 15:44:46.993927       1 network_routes_controller.go:762] Could not find BGP peer info for the node in the node annotations so skipping configuring peer.
I0206 15:44:46.994043       1 network_routes_controller.go:253] Shutting down network routes controller
time="2020-02-06T15:45:05Z" level=info msg="Can't find configuration for a new passive connection from:10.50.1.232" Topic=Peer
time="2020-02-06T15:45:09Z" level=info msg="Can't find configuration for a new passive connection from:10.50.3.66" Topic=Peer
time="2020-02-06T15:45:09Z" level=info msg="Can't find configuration for a new passive connection from:10.50.3.99" Topic=Peer
time="2020-02-06T15:45:11Z" level=info msg="Can't find configuration for a new passive connection from:10.50.5.46" Topic=Peer
```

As a fix I disabled this with `--disable-source-dest-check=false` and everything is ok, but I wanted to mention it.

Although I have a question, any  reason why kube-router would disable src/dest check for all the nodes, instead of doing only for the current node?

Tested with version `v0.4.0-rc3`

**Comment by murali-reddy** [comment] 2020-03-06 09:17
thanks for reproting the issue @renaudhager 

 >  kube router enter in a crash loop when it starts while it tries to disable src/dest check.

Perhaps there is a bug where kube-rotuer is not responding to health checks when it is performing diable of source-destination checks. We had issues due to aggressive EC2 API rate limiter which will reject too frequent calls, so kube-router invokes ec2 api with a delay in between.

https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/aws.go#L67

In your case may be it took 15 sec during that time it failed to responsd health check. I am marking it as bug for not to investigate further 

> Although I have a question, any reason why kube-router would disable src/dest check for all the nodes, instead of doing only for the current node?

Not all nodes of necessary IAM to access AWS EC2 API (https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md) so master nodes perform src-dst disable check for all the nodes.

**Comment by aauren** [comment] 2020-04-25 08:31
Closing as duplicate of #407 

Heads up @murali-reddy the performance of these bulk src/dst disable has been the source of several tickets and seems to be long standing

**Closed by aauren** 2020-04-25 08:31 UTC
Labels: bug
