### ISSUE TITLE
Nodes in same subnet, cannot reach pods on a newly created node

### ISSUE THREAD

**Issue by mzeeshan1** [cloudnativelabs/kube-router#1559] opened 2023-10-16 09:51 UTC
**What happened?**
When a new node joins cluster, the pods on other nodes (in same subnet) cannot reach pods on newly joined node.

**What did you expect to happen?**
Pods on other nodes( in same subnet) should be able to reach pods on newly joined node

**How can we reproduce the behavior you experienced?**
I have the following setup,
Spin up a kubernetes cluster with kops, with kubernetes version 1.24.16.  

** System Information (please complete the following information):**
 - Kube-Router Version : 1.5.0/1.6.0/2.0.0
 - Kube-Router Parameters: 
--run-router=true --run-firewall=true --run-service-proxy=true --bgp-graceful-restart=true --kubeconfig=/var/lib/kube-router/kubeconfig --metrics-port=12013
 - Kubernetes Version 1.24.16
 - Cloud Type: aws
 - Kubernetes Deployment Type: Kops
 - Kube-Router Deployment Type: Daemonset
 - Cluster Size: 10 worker nodes, 1 control plane node

**Additional context**
The problem does not appear when kubernetes version is downgraded to 1.23.17 but it reappears when kubernetes version is updated to 1.24.16. A restart of kube router, normally on the control plane fixes the connectivity problem until a new node joins. Same setup is tried with another CNI calico, and issue does not occur. It only happens with kube-router.
The bgp peering seems to be established between the faulty nodes. Routes are also added. Connectivity still doesn't seem to work until kube-router on control-plane is restarted.

**Comment by sinaabadi** [comment] 2023-10-18 11:50
@aauren could you please have a look at this issue?

**Comment by aauren** [comment] 2023-10-19 22:02
This sounds like there is likely something wrong with the node setup or the networking environment. I have several clusters on Kubernetes 1.24 and I have not been able to reproduce this issue.

Additionally, there is nothing special about the kube-router node that runs on the control plane in terms of orchestrating the cluster, so I'm not sure how restarting that instance of kube-router would have an impact on the cluster.

I think that you would need to do some additional troubleshooting to prove out that this is a bug in kube-router before we could proceed with helping you on this issue.

**Comment by mzeeshan1** [comment] 2023-10-20 02:20
I could not reproduce the same issue with calico. If it indeed was an issue with networking environment, it would have been an issue with calico as well. Calico also setup a similar network as kube router for pod network connectivity between nodes. It also seemed strange to me that restarting kube router node on control plane fixes the issue but it does. Are your clusters setup with kops also?

**Comment by aauren** [comment] 2023-10-20 02:35
No, I don't have access to a KOPS cluster right now. Unfortunately, there are a lot of differences between Calico and kube-router, so that doesn't really narrow it down.

You'll need to do some additional troubleshooting on your side before there is anything actionable here.

**Comment by mzeeshan1** [comment] 2023-10-20 04:00
@aauren I am certain that if you set up a cluster with kops (preferably 1.27.0 version), Kubernetes 1.24 with kube-router as a CNI, you will hit the same issue. The fact that a restart of kube-router node fixes the issue suggests to me that it is indeed a kube-router issue besides it is kube-router's responsibility to establish pod-to-pod network connectivity, which it is not doing so in this case. Kops also might be playing a part here but I cannot say for 100% as I have not tried to setup a cluster with another tool. 
Please let me know how can I verify that it s not a kube-router issue?

**Comment by aauren** [comment] 2023-10-20 15:02
I've done as you've said, and spun up a kops cluster, I'm not able to reproduce your results.

```sh
$ kops create cluster --name=${NAME} --cloud=aws --zones=us-east-1b --discovery-store=<omitted> --networking kube-router --kubernetes-version v1.24.16

$ kops update cluster --name kube-router.shadowslab.com --yes --admin

# Wait until cluster is active and healthy

$ kubectl get nodes -o wide                                                                                                            
NAME                  STATUS   ROLES           AGE     VERSION    INTERNAL-IP      EXTERNAL-IP       OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
i-0c538f0a370f0f76a   Ready    node            9m28s   v1.24.16   172.20.55.113    <omitted>      Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-0dd90f0756e982493   Ready    control-plane   12m     v1.24.16   172.20.121.198   <omitted>   Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21

# Apply a simple daemonset workload
$ cat whoami.yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    #kube-router.io/service.dsr: tunnel
    kube-router.io/service.local: "true"
    purpose: "Creates a VIP for balancing an application"
  labels:
    name: whoami
  name: whoami
  namespace: default
spec:
  ports:
  - name: flask
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: whoami
  type: LoadBalancer

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whoami
  namespace: default
spec:
  selector:
    matchLabels:
      name: whoami
  template:
    metadata:
      labels:
        name: whoami
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: whoami
          image: "docker.io/containous/whoami"
          imagePullPolicy: Always
          command: ["/whoami"]
          args: ["--port", "5000"]

$ kubectl apply -f whoami.yml

# Check pods
$ kubectl get pods -n default -o wide                                                                                                                                                                                                                                                                      
NAMESPACE     NAME                                            READY   STATUS    RESTARTS      AGE     IP               NODE                  NOMINATED NODE   READINESS GATES                                                                                                           
default       whoami-jljz5                                    1/1     Running   0             3m11s   100.96.0.3       i-0dd90f0756e982493   <none>           <none>                                                                                                                    
default       whoami-lrlfl                                    1/1     Running   0             3m11s   100.96.1.8       i-0c538f0a370f0f76a   <none>           <none>

# Run a debug container to ensure that I can get to all pods
$ kubectl debug -it whoami-jljz5 --image=nicolaka/netshoot --target=whoami --share-processes=true
whoami-jljz5% ip addr                                                                                                                                                                                                                                                                   
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000                                                                                                                                                                                             
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00                                                                                                                                                                                                                               
    inet 127.0.0.1/8 scope host lo                                                                                                          
       valid_lft forever preferred_lft forever                                                                                                                                                                                                                                          
    inet6 ::1/128 scope host                                                                                                                                                                                                                                                            
       valid_lft forever preferred_lft forever
3: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default 
    link/ether b2:4a:df:a1:f2:f3 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.96.0.3/24 brd 100.96.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b04a:dfff:fea1:f2f3/64 scope link 
       valid_lft forever preferred_lft forever
whoami-jljz5% ping 100.96.1.8
PING 100.96.1.8 (100.96.1.8) 56(84) bytes of data.
64 bytes from 100.96.1.8: icmp_seq=1 ttl=62 time=0.882 ms
64 bytes from 100.96.1.8: icmp_seq=2 ttl=62 time=0.362 ms
^C
--- 100.96.1.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1015ms
rtt min/avg/max/mdev = 0.362/0.622/0.882/0.260 ms
whoami-jljz5% ping 172.20.55.113
PING 172.20.55.113 (172.20.55.113) 56(84) bytes of data.
64 bytes from 172.20.55.113: icmp_seq=1 ttl=63 time=0.416 ms
^C
--- 172.20.55.113 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.416/0.416/0.416/0.000 ms

# Expand the node group in the same subnet
$ kops edit ig nodes-us-east-1b # increase minSize

# Apply changes
$ kops update cluster --yes

# Wait for node to join cluster and cluster to be healthy
$ kubectl get nodes -o wide
NAME                  STATUS   ROLES           AGE   VERSION    INTERNAL-IP      EXTERNAL-IP       OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
i-054e152644319a1ea   Ready    node            65s   v1.24.16   172.20.174.46    <omitted>       Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-0c538f0a370f0f76a   Ready    node            12m   v1.24.16   172.20.55.113    <omitted>      Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-0dd90f0756e982493   Ready    control-plane   15m   v1.24.16   172.20.121.198   <omitted>  Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21

# Check that daemonset has scaled out
$ kubectl get pods -n default -o wide
NAMESPACE     NAME                                            READY   STATUS    RESTARTS      AGE     IP               NODE                  NOMINATED NODE   READINESS GATES
default       whoami-jljz5                                    1/1     Running   0             7m24s   100.96.0.3       i-0dd90f0756e982493   <none>           <none>
default       whoami-lrlfl                                    1/1     Running   0             7m24s   100.96.1.8       i-0c538f0a370f0f76a   <none>           <none>
default       whoami-vhtxj                                    1/1     Running   0             17s     100.96.2.3       i-054e152644319a1ea   <none>           <none>

# Run debug container and check that new pod on new node (100.96.2.3) is reachable
$ kubectl debug -it whoami-jljz5 --image=nicolaka/netshoot --target=whoami --share-processes=true
whoami-jljz5% ping 100.96.2.3
PING 100.96.2.3 (100.96.2.3) 56(84) bytes of data.
64 bytes from 100.96.2.3: icmp_seq=1 ttl=62 time=0.931 ms
64 bytes from 100.96.2.3: icmp_seq=2 ttl=62 time=0.367 ms
^C
--- 100.96.2.3 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.367/0.649/0.931/0.282 ms
whoami-jljz5% ping 100.96.1.8
PING 100.96.1.8 (100.96.1.8) 56(84) bytes of data.
64 bytes from 100.96.1.8: icmp_seq=1 ttl=62 time=0.423 ms
64 bytes from 100.96.1.8: icmp_seq=2 ttl=62 time=0.373 ms
^C
--- 100.96.1.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1021ms
rtt min/avg/max/mdev = 0.373/0.398/0.423/0.025 ms
whoami-jljz5% curl http://100.96.2.3:5000
Hostname: whoami-vhtxj
IP: 127.0.0.1
IP: ::1
IP: 100.96.2.3
IP: fe80::dc64:dbff:fe24:418c
RemoteAddr: 100.96.0.3:37108
GET / HTTP/1.1
Host: 100.96.2.3:5000
User-Agent: curl/8.0.1
Accept: */*
```

I'm not sure what's going on in your kops environment, but this doesn't have to do with kube-router.

Closing this issue as invalid.

**Closed by aauren** 2023-10-20 15:02 UTC
Labels: bug

**Comment by mzeeshan1** [comment] 2023-10-20 23:40
@aauren I was able to reproduce the issue with the test case you have performed but with a slight difference. The difference was that I added one more node in the cluster. The added node had the same issue (pod subnet not reachable from another node. 

`
## create a new cluster
kops create cluster --name=test-cluster-2.k8s.local --zones=eu-central-1a,eu-central-1b,eu-central-1c --kubernetes-version v1.24.16 --networking kube-router --cloud was

#Wait for cluster to spin up

#update the cluster (standard kops step)
kops update cluster --name=test-cluster-2.k8s.local --yes --admin

A new kubernetes version is available: 1.24.17
Upgrading is recommended (try kops upgrade cluster)

More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.24.17

*********************************************************************************

I1021 03:23:23.976029    3491 executor.go:111] Tasks: 0 done / 115 total; 47 can run
W1021 03:23:24.822078    3491 vfs_keystorereader.go:143] CA private key was not found
I1021 03:23:24.991015    3491 keypair.go:226] Issuing new certificate: "etcd-manager-ca-main"
I1021 03:23:25.005250    3491 keypair.go:226] Issuing new certificate: "etcd-peers-ca-main"
I1021 03:23:25.006951    3491 keypair.go:226] Issuing new certificate: "etcd-peers-ca-events"
I1021 03:23:25.026307    3491 keypair.go:226] Issuing new certificate: "apiserver-aggregator-ca"
I1021 03:23:25.147622    3491 keypair.go:226] Issuing new certificate: "etcd-clients-ca"
I1021 03:23:25.172906    3491 keypair.go:226] Issuing new certificate: "etcd-manager-ca-events"
W1021 03:23:25.317432    3491 vfs_keystorereader.go:143] CA private key was not found
I1021 03:23:25.485477    3491 keypair.go:226] Issuing new certificate: "kubernetes-ca"
I1021 03:23:25.514891    3491 keypair.go:226] Issuing new certificate: "service-account"
I1021 03:23:28.564290    3491 executor.go:111] Tasks: 47 done / 115 total; 21 can run
I1021 03:23:30.811217    3491 executor.go:111] Tasks: 68 done / 115 total; 27 can run
I1021 03:23:33.848550    3491 executor.go:111] Tasks: 95 done / 115 total; 4 can run
I1021 03:23:34.760094    3491 executor.go:111] Tasks: 99 done / 115 total; 8 can run
I1021 03:23:37.187995    3491 executor.go:111] Tasks: 107 done / 115 total; 4 can run
I1021 03:23:39.582893    3491 executor.go:111] Tasks: 111 done / 115 total; 4 can run
I1021 03:23:40.058289    3491 executor.go:111] Tasks: 115 done / 115 total; 0 can run
I1021 03:23:40.094341    3491 update_cluster.go:323] Exporting kubeconfig for cluster
kOps has set your kubectl context to test-cluster-2.k8s.local

Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * validate cluster: kops validate cluster --wait 10m
 * list nodes: kubectl get nodes --show-labels
 * ssh to a control-plane node: ssh -i ~/.ssh/id_rsa ubuntu@
 * the ubuntu user is specific to Ubuntu. If not using Ubuntu please use the appropriate user based on your OS.
 * read about installing addons at: https://kops.sigs.k8s.io/addons.

#validate the cluster (standard kops step) and wait for cluster to be vaildated
kops validate cluster --wait 10m
# wait for cluster to be validated


kops get ig   
                                   
Using cluster from kubectl context: test-cluster-2.k8s.local

NAME                            ROLE            MACHINETYPE     MIN     MAX     ZONES
control-plane-eu-central-1a     ControlPlane    t3.medium       1       1       eu-central-1a
nodes-eu-central-1a             Node            t3.medium       1       1       eu-central-1a
nodes-eu-central-1b             Node            t3.medium       1       1       eu-central-1b
nodes-eu-central-1c             Node            t3.medium       1       1       eu-central-1c

kops edit ig nodes-eu-central-1a
# I repeated this step a couple of times, first time I added 3 nodes to ig. Then I modified ig and added one more node. When I modified ig 2nd time I faced the issue again. Find workflow below

cat whoami

apiVersion: v1
kind: Service
metadata:
  annotations:
    #kube-router.io/service.dsr: tunnel
    kube-router.io/service.local: "true"
    purpose: "Creates a VIP for balancing an application"
  labels:
    name: whoami
  name: whoami
  namespace: default
spec:
  ports:
  - name: flask
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: whoami
  type: LoadBalancer

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whoami
  namespace: default
spec:
  selector:
    matchLabels:
      name: whoami
  template:
    metadata:
      labels:
        name: whoami
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: whoami
          image: "docker.io/containous/whoami"
          imagePullPolicy: Always
          command: ["/whoami"]
          args: ["--port", "5000"]



kubectl apply -f whoami                                                                                                                                       
service/whoami created
daemonset.apps/whoami created

kubectl get nodes -o wide
NAME                  STATUS   ROLES           AGE   VERSION    INTERNAL-IP      EXTERNAL-IP     OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
i-00cb17a339e73d357   Ready    node            60m   v1.24.16   172.20.71.235    18.198.27.249   Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-0793f657d846441b6   Ready    node            36m   v1.24.16   172.20.54.28     54.93.83.152    Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-0827def0d2b4f503e   Ready    node            60m   v1.24.16   172.20.118.114   3.75.99.110     Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-086230d4166aa9cdd   Ready    node            45m   v1.24.16   172.20.54.60     18.195.213.20   Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-09cd5476a1c0f8bc8   Ready    node            60m   v1.24.16   172.20.50.107    3.75.190.35     Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-0d1d4a85d62d7586e   Ready    node            45m   v1.24.16   172.20.34.170    3.76.220.223    Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21
i-0db85ada3b50ca2da   Ready    control-plane   62m   v1.24.16   172.20.60.213    52.59.209.199   Ubuntu 20.04.6 LTS   5.15.0-1045-aws   containerd://1.6.21

kubectl get pods -n default -o wide
NAME           READY   STATUS    RESTARTS   AGE   IP           NODE                  NOMINATED NODE   READINESS GATES
whoami-bhhhh   1/1     Running   0          63s   100.96.0.3   i-0db85ada3b50ca2da   <none>           <none>
whoami-f4rc2   1/1     Running   0          63s   100.96.6.4   i-0793f657d846441b6   <none>           <none>
whoami-fm7s7   1/1     Running   0          63s   100.96.4.3   i-0d1d4a85d62d7586e   <none>           <none>
whoami-pbpfm   1/1     Running   0          63s   100.96.1.5   i-09cd5476a1c0f8bc8   <none>           <none>
whoami-qp9ck   1/1     Running   0          63s   100.96.2.4   i-0827def0d2b4f503e   <none>           <none>
whoami-tcr8w   1/1     Running   0          63s   100.96.5.4   i-086230d4166aa9cdd   <none>           <none>
whoami-vkd4g   1/1     Running   0          63s   100.96.3.3   i-00cb17a339e73d357   <none>           <none>



kubectl debug -it whoami-tcr8w --image=nicolaka/netshoot --target=whoami --share-processes=true 
Targeting container "whoami". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-pd5gf.
If you don't see a command prompt, try pressing enter.
whoami-tcr8w% ping 100.96.6.4
PING 100.96.6.4 (100.96.6.4) 56(84) bytes of data.





^C
--- 100.96.6.4 ping statistics ---
17 packets transmitted, 0 received, 100% packet loss, time 16382ms


Please excuse my data presentation, it is not the best and not fully in order (as I first performed the steps and then started documenting them so I had performed some unnecessary steps but please be assured that it does not meddle with test results at all.

`

**Comment by aauren** [comment] 2023-10-21 21:51
So, I just can't reproduce this...

I tried the following scenario:

* start cluster with 1 control 1 worker - both instances were ping-able and curl-able
* added 3 workers - all workers were ping-able and curl-able
* added 1 worker - all workers were ping-able and curl-able
* added 5 workers (total 11 at this point) - all workers were ping-able and curl-able
* added 1 worker  - all workers were ping-able and curl-able

One thing that I did notice throughout was that after I added the additional 3 workers, the pod on the control plane was not ping-able, however, it was still curl-able. Looking at the Security Group that kOps adds specifically to the control plane nodes I noticed that it doesn't allow ICMP traffic like the workers security group does. After added an inbound rule for ICMP traffic to the master node security group I was able to ping the pod on the control plane.

However, I don't think that's what you're experiencing as your logs above show that the pod that you lost packets to was on a regular node not the control plane node.

Sorry, I don't think that there is anything more that I can do to help you it really seems like there is something specific to your environment that is going on.

**Comment by mzeeshan1** [comment] 2023-11-21 10:16
@aauren I don't know how is it working for you. I have tried below:
Setup a new aws account, spin up cluster with kops with kube-router as cni and I still face the issue and only kube-router restart fixes it. It is 100% reproducible. I am sharing the versions I am using below, can you please also share the versions you used in your tests, we can compare what is different in my env

kops: Client version: 1.27.0 (git-v1.27.0)
kubernetes: 1.24.16
OS: Ubuntu 20.04.6 LTS Kernel: 5.15.0-1047-aws
OS Image ID: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20231004
Container Runtime: containerd://1.6.21
KubeRouter: v1.5.3@sha256:1ff68d43debb9397e121c53554ef392c72b199d9c07714b0e50e179e1edce052
