### ISSUE TITLE
BGP Configuration link broken

### ISSUE THREAD

**Issue by joestringer** [cloudnativelabs/kube-router#933] opened 2020-06-15 23:54 UTC
Browsing to the following page in the docs:

https://www.kube-router.io/docs/user-guide/#bgp-configuration

When I try to click "Configuring BGP Peers", it brings me to:

https://www.kube-router.io/docs/user-guide/bgp.md

And the page is a 404 not found page.

**Comment by aauren** [comment] 2020-06-16 01:21
Closing as duplicate of #814

**Closed by aauren** 2020-06-16 01:21 UTC
