### ISSUE TITLE
When IPSEC in transport mode is enabled between nodes, packets from nodes to services never return

### ISSUE THREAD

**Issue by FabienZouaoui** [cloudnativelabs/kube-router#877] opened 2020-04-14 20:14 UTC
When IPSEC in transport mode is enabled between nodes, I cannot reach services IPs exposed from local IPs (ex: apiserver) from nodes anymore.
Nodes are not in the same network, so communication is enabled through ipip tunnels.
Pods IP are still accessible. 
Everything works without IPSEC.

This is linked to the routing rule created when a new IP is added to ipvs.
This rule force local IP as source, this result in:
. Tunneling with the same ip source and same ip dest.
. I think that the returning packet is NATED by ipvs before being un-encapsuled or considered martian when send through the tunnel.

#876 fix this by using bridge ip source for the routing rule

**Comment by murali-reddy** [comment] 2020-04-23 19:06
@FabienZouaoui Sorry I am not able to follow what the issue is. Can you please elobrate

> I cannot reach services IPs exposed from local IPs (ex: apiserver) from nodes anymore.
Nodes are not in the same network, so communication is enabled through ipip tunnels.
Pods IP are still accessible.

> This is linked to the routing rule created when a new IP is added to ipvs.

Can you share what routing rule you are referring to?

#876 I am afraid goes againest the design of kube-router. Service proxy part of kube-router should be usable with other CNI's as well. Harcoding with `kube-bridge` will defeat the goal.

**Comment by FabienZouaoui** [comment] 2020-04-24 14:49
@murali-reddy thanks for your reply.

> Can you share what routing rule you are referring to?
I'm referring to the rule created by ipAddrAdd() method [here](https://github.com/cloudnativelabs/kube-router/blob/ffad3388a9b6e24ed22690b92eeeeacb6b7b48e4/pkg/controllers/proxy/network_services_controller.go#L146)

> #876 I am afraid goes against the design of kube-router. Service proxy part of kube-router should be usable with other CNI's as well. Harcoding with kube-bridge will defeat the goal.
I can add an optional switch to specify on which interface the source IP address should be picked up  if you think there is an hope for this PR

Let me use an theoretical example to clarify my problem:
- node1 lan_ip = 192.168.1.1/24
- node2 lan_ip = 192.168.2.1/24

My kubernetes api servers are advertising their lan_ip adress on each node, so I have those endpoints for the kubernetes service: 192.168.1.1:6443,192.168.2.1:6443

When I try to access this service from node1 and ipvs nat traffic to node 2:
Syn is correctly received by node2 and I can capture the Syn ack arriving on node1 but it is silently dropped somewhere.
I was wrong about the tunneling, the packet is sent as-is after beeing natted by ipvs. Sorry.

I think this problem is a sort of incompatibility between ipvs and ipsec.
Using kube-bridge's ip as source works around it by encapsulating traffic in an ipip tunnel (I'm not 100% sure on what exactly happen here)

**Comment by FabienZouaoui** [comment] 2020-04-27 04:50
A better approach for #876 can be adding a new flag that disable route creation (--enable-service-route-creation=false ?).
This way I can manage my own routing rules without being bothered by this feature

**Comment by aauren** [comment] 2020-08-31 16:48
Closing this issue as it's pretty old for now and it supports a use-case that is not all that prominent. In the stage where kube-router is currently we need to reduce our focus so that we can better support more of the mainstream use-cases. In general, cloud native seems to be rallying around service mesh to support end-to-end encryption which gives not only the encryption that ipsec would give but also provides authentication and authorization for that encrypted payload.

That being said, it's possible that other initiatives that we plan to support may ultimately help you along the way, maybe something like: https://github.com/cloudnativelabs/kube-router/issues/979 which controls which services are monitored by the Kubernetes service proxy?

**Closed by aauren** 2020-08-31 16:48 UTC

**Comment by opg7371** [comment] 2022-03-14 06:48
@FabienZouaoui Sorry to open this issue after so long.
Client A --------------> Service (Master Node) ------------------> Worker Node(Pod)
The XFRM associations are made at Client A and Pod. Client A sends IPSec Transport mode to service external Ip which should be forwarded to Pod.

But, the ESP packet gets stuck at the master node. It is very similar to your situation where a hop arises in case of IPSec TRANSPORT mode (which is end to end). Can you please suggest me as to how to solve this issue?

Should eBPF of celium or creating bridge network between master and pods do the trick?

**Comment by ramank24** [comment] 2022-03-14 09:24
In our case we were facing same issue but our communication was between Client A and WorkerNode(Pod). So worker node was dropping esp packets. 

This was resolved by making the Docker/Container NameSpace same as that of Host name space(Worker Node Namespace).
But your requirement is different and we will also support any help to resolve this issue. 
Kindly keep this open.

**Comment by FabienZouaoui** [comment] 2022-03-14 10:05
@opg7371 No problem, I'll be happy to provide a bit of help if I can.
I'm not sure that your problem is the same than mine.

My problem was IPVS doing NAT after ipsec encryption.
My (not very elegant) workaround is to force encapsulation in the ipip tunnel created by kube-router so encryption is performed on the ipip packet after NAT.

To do that, I have to modify which ip address is used by kube-router to update routing rules: https://github.com/cloudnativelabs/kube-router/compare/v1.3.1...SirDataFR:use-bridge-ip-as-source-and-disable-snat

Please note that I have not synced since v1.3.1 and I'm also disabling masquerading for an unrelated reason.

To test if you encounter the same problem than me without running a modified version of kube-router, you can write a small script to update routes more frequently than kube-router with the bridge ip as source.

Hope this helps
