### ISSUE TITLE
Allow custom rule in FORWARD chain

### ISSUE THREAD

**Issue by anupamdialpad** [cloudnativelabs/kube-router#1353] opened 2022-08-30 11:29 UTC
A custom rule in the FORWARD chain of iptables added manually is removed by kube-router during iptables-sync. Is there a way to overcome this?

**Comment by aauren** [comment] 2022-08-30 21:41
kube-router does not do this, it will only ever insert or append rules to the built-in chains. The two portions of the code that manipulate the FORWARD chain can be found here:
* https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/network_routes_controller.go#L865-L909
* https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/netpol/network_policy_controller.go#L293-L417

If your forwarding rules are being deleted it is likely that something other than kube-router is doing it. Closing this for now as I'm not able to reproduce this problem locally.

If you're certain that its kube-router doing this, we would need a lot more debugging information that conclusively proves kube-router is doing this to proceed.

**Closed by aauren** 2022-08-30 21:41 UTC
Labels: feature
