### ISSUE TITLE
kube-router doesn't work when Nodes are on different subnet

### ISSUE THREAD

**Issue by imranrazakhan** [cloudnativelabs/kube-router#972] opened 2020-08-19 12:17 UTC
I deployed three node K8S cluster and each node is in different subnet, After that i observed my app was on node1 and Database was on node2, my app was not able to access db service. As soon as i changed from kube-router to flannel everything start working as expectation. 

** System Information (please complete the following information):**
 - Kube-Router Version (`kube-router --version`):  1.0.1
 - Kubernetes Version (`kubectl version`) :  1.18.6
 - Kubernetes Deployment Type: Kubeadm (BareMetal)
 - Kube-Router Deployment Type:  DaemonSet
 - Cluster Size: 3 nodes

**Comment by aauren** [comment] 2020-08-19 17:40
You'll have to provide more details around this in order for us to be able to help you. I know that I personally run more than 10 clusters with nodes in all different subnets and have no problems using kube-router.

I'm closing this for now due to lack of information, but if you add additional details about your configuration and debugging I'm more than happen to re-open it. These are all things that would have been clearer if you had followed the guidance of the issue template.

Helpful details would be:
- Steps to reproduce this issue
- Network topology / architecture diagram
- Logs from kube-router
- Metrics
- A traceroute between nodes
- A traceroute between pods
- A list of the parameters you used to run kube-router

**Closed by aauren** 2020-08-19 17:40 UTC
Labels: bug

**Comment by imranrazakhan** [comment] 2020-12-09 21:38
@aauren  Sorry for late reply, due to project timeline i was not able to update, Although i am now using flannel but i fixed this issue

**Environment:**
I have 3 nodes  cluster
Operating System: CentOS 7.8
kubernetes: 1.19.2 
kube-router: 1.1.0

- I thought i am facing issue due to different subnet, infact problem was that Kubernetes pod cannot access service which is running on another node. e.g I have to schedule MySQL and Client pod on same node to make it work.

I fixed issue by disabling firewalld, i dont know what port/rules suppose to be add to make kube-router work with firewalld, please point me to document.

**Comment by aauren** [comment] 2020-12-10 01:57
I'm glad that you were able to determine what the problem was.

Working with various OS firewall rules is always difficult and prone to error. I know that we made a concerted effort a while back to accommodate firewalld by changing the order in which rules are inserted: https://github.com/cloudnativelabs/kube-router/pull/596

However, they may have changed the logic behind firewalld upstream or maybe there are custom rules that have been added in your environment. In the end, kube-router makes an effort to only be authoritative for pod rules, but custom firewall software can and does interfere with that and it will be up to the user to work through issues when they arise.
