### ISSUE TITLE
Stale service IPs are still not fully cleaned up?

### ISSUE THREAD

**Issue by johanot** [cloudnativelabs/kube-router#438] opened 2018-05-14 12:54 UTC
This one puzzles me a bit.. kube-router logs: 

> Found an IP 10.232.37.229 which is no longer needed so cleaning up

, the deletion of the address then later fails silently, because that IP address is *not* assigned to kube-dummy-if.
Silent failure is not entirely true, because lldpd on the node complaints with:
> lldpd[1440]: removal request for address of 10.232.37.229%10, but no knowledge of it

On my container-node in question:

`ip addr show |grep 10.232.37.229`
(no match)

however (below gives a match)

`ip route show table all |grep 10.232.37.229`
> local 10.232.37.229 dev kube-dummy-if table local proto kernel scope host src 172.20.33.4

Trying to look deeper into https://github.com/vishvananda/netlink, but I'm not that strong in which-syscall-does-what. However, it looks like: https://github.com/vishvananda/netlink/blob/master/addr_linux.go#L147 returns an address which is *not* assigned to the dummy-if - and perhaps the cause is, that a route still exist in the local routing table?

Perhaps the problem is as simple as: Stale IPs are now removed from the kube-dummy-if (thanks to https://github.com/cloudnativelabs/kube-router/pull/417), but **not** from the routing table?

@murali-reddy @dlamotte ?

**Comment by murali-reddy** [comment] 2018-05-14 13:13
@johanot thanks for reporting the issue.

I think it perhaps a regression from #433, there is explict route added in `local` routing table to use node IP when accessing the service VIP's assigned to the `kube-dummy-if`. 

I will test and fix it if needed.

**Comment by johanot** [comment] 2018-05-14 14:26
AFAIK no issues other than log noise for every reconcile cycle. :) But of course this could potentially lead to performance issues in case of a high number of service IPs.

**Comment by aauren** [comment] 2020-07-10 07:49
We've touched a lot of the code surrounding service vips since this issue was opened. Closing this as I'm not able to reproduce on my current cluster. Feel free to re-open if you're still seeing this issue.

**Closed by aauren** 2020-07-10 07:49 UTC
Labels: bug
