### ISSUE TITLE
kube-router doesn't work with containerd out of the box

### ISSUE THREAD

**Issue by farcaller** [cloudnativelabs/kube-router#548] opened 2018-10-01 15:28 UTC
containerd is oblivious to the injected cni config so it needs to be restarted after kuberouter creates the config. filing here because calico seems to work fine for whatever reason.

**Comment by menardorama** [comment] 2018-10-23 23:29
Having similar problem with containerd and kube-router on kubernetes 1.11.
My case is that I can’t resolve kubernetes.default.... it’s Quite annoying.

A node reboot generaly solve the issue but that’s basically impossible to do in a prod env

**Comment by aauren** [comment] 2020-04-25 04:22
Duplicate of #286

**Closed by aauren** 2020-04-25 04:22 UTC
