### ISSUE TITLE
v1.5.0 external bgp connection fails

### ISSUE THREAD

**Issue by rkojedzinszky** [cloudnativelabs/kube-router#1391] opened 2022-11-02 09:33 UTC
**What happened?**
Upgraded from v1.4 to v1.5, and external bgp peer connections failed to estabilish.

**What did you expect to happen?**
Expected external bgp sessions to come up as before.

**How can we reproduce the behavior you experienced?**
1. Have a node with two (or more L3) interfaces, one said to be k8s backbone, and one facing an external router
2. Annotate the node to have the external bgp configuration
3. Restart kube-router on node
4. Observe `Mismatched local address` log messages in kube-router's log

**Additional context**
I suspect 184976a5369920ec176da961e61de739726be5fb causes the change. Perhaps,  it would be helpful to specify a localaddress for peers via annotations the same way as other parameters.

**Comment by aauren** [comment] 2022-11-02 15:00
Closing this as a duplicate of #1371

**Closed by aauren** 2022-11-02 15:00 UTC
Labels: bug
