### ISSUE TITLE
AWS scaling issues - RequestLimitExceeded when disabling src dest checks.

### ISSUE THREAD

**Issue by dvianello** [cloudnativelabs/kube-router#664] opened 2019-02-08 11:32 UTC
Hi there,

trying to use `kube-router` in a `kops` deployment in AWS, we're encountering issues when scaling up via Cluster Autoscaler. 

Our initial deployment is usually just 1 master + 2 nodes. We then use Cluster Autoscaler to keep an eye on the number of pods that can't be scheduled and adjust cluster size accordingly. Sometimes this might mean ~50 nodes joining in the space of a couple of minutes. What we see in this case is `kube-router` trying to disable src/dest check in all the instances, hitting AWS API request limits so that `kube-router` pods start to fail end eventually go into `CrashLoopBackOff`. This basically means we completely lose networking, pods get stuck and so on. Not nice :-) 

I've dumped logs from the instance of `kube-router` running on master, a randomly-picked `kube-router` running on a node and a quick `kubectl get pods` in this gist: https://gist.github.com/dvianello/ebf0c9d6513a0eec756ea39aad9a598c

As you can see many of the `kube-router` pods do restart many times and eventually go into `CrashLoopBackOff`. The cluster eventually (~10 minutes for a 50 nodes cluster) recovers, but any scaling up triggers this again. This is a big issue for us, and we might need to look elsewhere, which is a pity. 

A few random thoughts, based on the logs: 
- why is `kube-router` on the master node trying to disable src/dest checks multiple times? The same instance id comes up many times in those logs. Is this expected?
- why is `kube-router` on the "random" node trying to disable src/dest on _other_ nodes even if it knows it can't actually do it?
- any way to fail more gracefully if src/dest disabling doesn't work because of throttling?

Even gradually scaling up by 10 nodes at a time sometimes causes issues! 

Happy to help in debugging if requires, as this is a bit of a big one for us. 

Tightly related to #313, #536 and #617. 

Cheers,
Dario

**Comment by zegl** [comment] 2019-02-12 08:07
A suggestion is planned in #407

**Comment by aauren** [comment] 2020-04-24 06:34
Closing as duplicate of #407

**Closed by aauren** 2020-04-24 06:34 UTC
