### ISSUE TITLE
Some log messages breaks log semantics

### ISSUE THREAD

**Issue by roffe** [cloudnativelabs/kube-router#251] opened 2017-12-15 13:20 UTC
Was going through my kube-router logs today and this catched my eye as the log format differs very much from the other lines

```
I1215 12:03:47.212844       1 network_routes_controller.go:517] Advertising route: '10.50.2.193/32 via 192.168.200.201' to peers
I1215 12:03:47.212878       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
I1215 12:03:47.212886       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
I1215 12:03:47.212974       1 network_routes_controller.go:242] Performing periodic syn of the routes
I1215 12:03:47.215401       1 network_routes_controller.go:365] Advertising route: '10.32.0.0/24 via 192.168.200.201' to peers
I1215 12:03:47.215611       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
time="2017-12-15T12:04:02Z" level=warning msg="received notification" Code=6 Data="[]" Key=192.168.200.1 Subcode=3 Topic=Peer
time="2017-12-15T12:04:02Z" level=warning msg="received notification" Code=6 Communicated-Reason= Data="[]" Key=192.168.200.1 Subcode=2 Topic=Peer
time="2017-12-15T12:04:02Z" level=info msg="Peer Down" Key=192.168.200.1 Reason="notification-received code 6(cease) subcode 3(peer deconfigured)" State=BGP_FSM_ESTABLISHED Topic=Peer
I1215 12:04:02.345986       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
time="2017-12-15T12:04:04Z" level=warning msg="Closed an accepted connection" Key=192.168.200.1 State=BGP_FSM_IDLE Topic=Peer
time="2017-12-15T12:04:04Z" level=warning msg="Closed an accepted connection" Key=192.168.200.1 State=BGP_FSM_IDLE Topic=Peer
I1215 12:04:40.949780       1 network_routes_controller.go:336] Processing bgp route advertisement from peer
I1215 12:04:47.123241       1 network_policy_controller.go:118] Performing periodic syn of the iptables to reflect network policies
I1215 12:04:47.124413       1 network_policy_controller.go:298] Iptables chains in the filter table are synchronized with the network policies.
I1215 12:04:47.129184       1 network_policy_controller.go:189] sync iptables took 5.912629ms
```
Would it be possible to make these messages conform to the logging format the rest of the application uses?

Cheers and thanks for a exciting piece of software

**Comment by murali-reddy** [comment] 2017-12-15 14:09
There is mismatch between the log libraries used by Kube-Router(glog) and GoBGP libarary(logrus) used in Kube-router. Other day over slack we were discussing to overhaul logging along with tracing #181. Enhancement is in order.

**Comment by aauren** [comment] 2020-04-24 05:55
Going to close this ticket out as I think that the tracing enhancement or a broader "overhaul logs" issue would be a better issue to track this work.

For now, given the existing log frameworks this is an eyesore but is working as intended.

**Closed by aauren** 2020-04-24 05:55 UTC
Labels: enhancement
