### ISSUE TITLE
Timeouts when doing rolling upgrades of pods behind service with type LoadBalancer

### ISSUE THREAD

**Issue by mikn** [cloudnativelabs/kube-router#467] opened 2018-06-14 12:19 UTC
This is sort of a preemptive issue as we're still in the middle of investigating this, but most arrows are currently pointing towards kube-router.
We have created a service that points to a deployment, this works fine until we trigger a rollout (or actually even just delete a pod in the replicaset). We have taken care to make sure our application terminates gracefully and see no signs of it receiving traffic after failing the first health-check (it mostly even gets removed from the service before failing the first health check).
We're currently not sure what goes wrong when a pod is deregistered from a service inside kube-router, but we will continue investigating tomorrow.
It may end up being closed because we fudged something, so don't spend it too much time yet. :)
(this is with externalTrafficPolicy: Cluster, by the way)
Thank you!

**Comment by mikn** [comment] 2018-07-09 07:47
After a rather in-depth investigation, this seems to be the issue we're hitting: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02
We are currently investigating a kube-router patch.

**Comment by aauren** [comment] 2020-04-24 07:15
Closing as duplicate of #455 please re-open if this is incorrect.

**Closed by aauren** 2020-04-24 07:15 UTC
