### ISSUE TITLE
kube-router and aws 

### ISSUE THREAD

**Issue by evilezh** [cloudnativelabs/kube-router#213] opened 2017-11-03 14:36 UTC
My setup:
AWS, ubuntu 16.04, kubeadm, 1.8.x.

- I patched all as per manual (for cloud setup) few weeks ago and everything was fine. (1.8.0), I did full rebuilds several times and was fine.
- today did full rebuild and figured out following.
  - version changed to 1.8.2
  - i can reach 192.168.x.x  (pod network) only if in same AZ.

Setup consists of kubeadm init, install kube-router, remove proxy, install dashboard, nginx ingress.
My nginx runs on hostNetwork (zone-a). I can reach services on other servers in zone-a. Anything in other zones just times out.

ipvsadm gives proper list of pod addresses (all entries present), when i try to reach - it just does not happen.

Any idea where to dig ?

**Comment by murali-reddy** [comment] 2017-11-03 16:52
@evilezh Was there a change in Kube-router version? We released 0.0.18 version yesterday.

Any changes to security groups you observe? Basically for cross-zone traffic IPIP tunneling is used. Please rule out the possibility that IPIP tunnel traffic is getting blocked.

Also when you access the service, do you connection count (Active conn) in IPVSadm is increasing atleast to one of the endpoints.

**Comment by looprock** [comment] 2017-11-07 21:42
I'm also having issues with cross-az traffic, though this is my first setup and I've never had it working to know if my setup is correct. Can someone point me at documentation for security groups? Here's what I have currently, where sg-5b626129 is the kops master node group and sg-2e55565c is the node security group. 

<img width="1158" alt="sg-2e55565c" src="https://user-images.githubusercontent.com/187808/32519381-2cf5df10-c3d2-11e7-94bb-5d94e9bd262d.png">

<img width="1146" alt="sg-5b626129" src="https://user-images.githubusercontent.com/187808/32519391-35c15be2-c3d2-11e7-99c3-249c1c0288f6.png">

**Comment by murali-reddy** [comment] 2017-11-08 01:52
@looprock there has been a regression on 0.0.18 release which made cross zone pod connectivity to not work. We will fix and make a new release.

**Comment by looprock** [comment] 2017-11-08 02:27
Thanks!

**Comment by murali-reddy** [comment] 2017-11-08 02:38
@looprock can you please give it a try now? `cloudnativelabs/kube-router:latest` or `cloudnativelabs/kube-router:v0.0.19` has the fix

**Comment by looprock** [comment] 2017-11-08 03:08
@murali-reddy I'm upstream using kops; I'd be happy to test but I'm unsure of how kops defines what version of kube-router it uses. I see you submitted a PR to kops so perhaps you could shed some light on how to get kops to use the new version? Thanks.

**Comment by murali-reddy** [comment] 2017-11-08 04:25
@looprock kops is setup to use latest release version

https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.kuberouter/k8s-1.6.yaml.template#L63

so if you just provision a new cluster, it automatically creates cluster with latest kube-router version.

**Comment by looprock** [comment] 2017-11-08 04:39
Nevermind, I just realized i only need to change the image in the container.. Routing seems to be fixed between service and pods. My external router can access services, but not individual pods and BGP still doesn't seem to be updating.

**Comment by looprock** [comment] 2017-11-13 19:07
This seems to be resolved for me and i'm moving the BGP routing issue to https://github.com/cloudnativelabs/kube-router/issues/221. Thanks again for your help!

**Comment by murali-reddy** [comment] 2017-11-13 19:17
Closing this issue as its fixed in latest release (0.0.19). please re-open if you are still running in to issues @evilezh

**Closed** 2017-11-14 03:26 UTC
