### ISSUE TITLE
ClusterIP/ExternalIP stops being announced after 5 minutes

### ISSUE THREAD

**Issue by bazuchan** [cloudnativelabs/kube-router#765] opened 2019-07-31 14:58 UTC
I upgraded to latest master and ClusterIP/ExternalIP stops being announced after 5 minutes (pod cidr announce still works). Version compiled on end of may from master works fine.

**Comment by murali-reddy** [comment] 2019-08-01 08:32
@bazuchan thanks for reporting. 

There is a regression in the master (https://github.com/cloudnativelabs/kube-router/pull/721#issuecomment-507751303) which is not fixed yet.

**Comment by aauren** [comment] 2019-08-19 23:01
This issue appears to be fixed by @tamihiro's change on #771

**Comment by andrewsykim** [comment] 2019-10-22 23:02
Looks like this was fixed, please reopen if you're still seeing this issue

**Closed by andrewsykim** 2019-10-22 23:02 UTC
Labels: bug
