### ISSUE TITLE
Enable iptables logging

### ISSUE THREAD

**Issue by MarkDeckert** [cloudnativelabs/kube-router#724] opened 2019-04-26 21:20 UTC
## Feature request:

Add a kube-router command line option to enable iptables log to file in the NetworkPolicyController.

## Reason:

This would help satisfy traditional enterprise security/auditing requirements.  It would be expected that the administrator would also deploy a fluentd daemonset or a tool like [kube-iptables-tailer](https://github.com/box/kube-iptables-tailer) to collect/ship the logs to an external source.

## Implementation:

The equivalent of these iptables arguments:

`-j LOG --log-prefix "EXAMPLE_LOG_PREFIX: "`

Ideally there would be additional kube-router command line flags so that log prefix can be customized/defined and so either all or only dropped (default) packets will be logged.  Usually the position within the chain that the log rule is added determines whether it will log all or only dropped packets.

eg:
--iptables-logging=false
--iptables-logging-prefix="kube-router-iptables:"
--iptables-logging-all-packets=false

**Comment by voidengineer** [comment] 2019-05-15 10:57
I am looking at kube-iptables-tailer too, and it would be great to have an integration here.

**Comment by aauren** [comment] 2020-04-25 07:17
Closing as duplicate of #505

**Closed by aauren** 2020-04-25 07:17 UTC
Labels: enhancement
